{% set name = "bycycle" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bycycle-tools/bycycle/archive/{{ version }}.tar.gz
  sha256: 78817687a95bd6ab3ff778603bb2c06c5ebe91a8fc4cced761996197e45f4b2e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy >=1.18.5
    - scipy >=1.4.1
    - pandas >=0.25.3
    - matplotlib-base
    - neurodsp >=2.1.0

test:
  imports:
    - bycycle
    - bycycle.burst
    - bycycle.cyclepoints
    - bycycle.features
    - bycycle.filt
    - bycycle.sim

about:
  home: https://github.com/bycycle-tools/bycycle
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Bycycle is a python implementation of a cycle-by-cycle approach to analyzing neural oscillations (Cole & Voytek, J Neurophysiol 2019).
  doc_url: https://bycycle-tools.github.io/bycycle/
  dev_url: https://github.com/bycycle-tools/bycycle

extra:
  recipe-maintainers:
    - ryanhammonds
